name: "on-pull-request"

on:
  pull_request:
    paths:
      - "application/**"

jobs:
  go-check-code-style:
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v5"

      - name: "Setup go"
        uses: "actions/setup-go@v6"
        with:
          go-version: "1.25.4"

      - name: "Check lint"
        uses: "golangci/golangci-lint-action@v8"
        with:
          working-directory: "./application"
          version: "latest"
          skip-cache: true
          args: "--timeout 2m"

  go-test:
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v5"

      - name: "Setup go"
        uses: "actions/setup-go@v6"
        with:
          go-version: "1.25.4"

      - name: "Run go mod tidy"
        working-directory: "./application"
        run: "go mod tidy"

      - name: "Install gotestsum"
        run: "go install gotest.tools/gotestsum@latest"

      - name: "Run unit tests"
        id: "ut-result"
        continue-on-error: true
        working-directory: "./application"
        run: "gotestsum --junitfile report.xml --format testname -- -cover -coverprofile=coverage.out -short ./..."

      - name: "Check if tests failed"
        if: "steps.ut-result.outcome == 'failure'"
        run: |
          echo "Unit test: ${{ steps.ut-result.outcome }}"
          exit 1
