---
name: "on-pull-request-cdk"

on:
  pull_request:

jobs:
  scan-vulnerability:
    runs-on: "ubuntu-latest"
    timeout-minutes: 3

    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v6"

      - name: "Setup node.js"
        uses: "./.github/actions/setup-node"
        with:
          working-directory: "./infrastructure/cdk"

      - name: "Check audit"
        run: "pnpm audit --audit-level high"
        working-directory: "./infrastructure/cdk"

  check-code-style:
    runs-on: "ubuntu-latest"
    timeout-minutes: 5
    needs:
      - "scan-vulnerability"

    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v6"

      - name: "Setup node.js"
        uses: "./.github/actions/setup-node"
        with:
          working-directory: "./infrastructure/cdk"

      - name: "Check code-style"
        run: "pnpm run ci ."
        working-directory: "./infrastructure/cdk"

  test:
    runs-on: "ubuntu-latest"
    timeout-minutes: 5
    needs:
      - "scan-vulnerability"

    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v6"

      - name: "Setup node.js"
        uses: "./.github/actions/setup-node"
        with:
          working-directory: "./infrastructure/cdk"

      - name: "Run test"
        run: "pnpm test"
        working-directory: "./infrastructure/cdk"
